<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TNAB.Network\TNAB.Network.csproj" />
    <ProjectReference Include="..\TNAB.Parsers\TNAB.Parsers.csproj" />
    <ProjectReference Include="..\TNAB.Browser\TNAB.Browser.csproj" />
    <ProjectReference Include="..\TNAB.Layout\TNAB.Layout.csproj" />
    <ProjectReference Include="..\TNAB.Renderer.SixLabors\TNAB.Renderer.SixLabors.csproj" />
  </ItemGroup>

</Project>
