<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TNAB.Parsers\TNAB.Parsers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.Fonts" Version="2.0.4" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
