<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <ArtifactsPivots>$(Configuration.ToLowerInvariant())_$(TargetFramework.ToLowerInvariant().Replace('-', "\"))</ArtifactsPivots>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TNAB.Browser\TNAB.Browser.csproj" />
    <ProjectReference Include="..\TNAB.Network\TNAB.Network.csproj" />
    <ProjectReference Include="..\TNAB.Renderer.Skia\TNAB.Renderer.Skia.csproj" />
  </ItemGroup>

  <Choose>
    <When Condition="$(TargetFramework.Contains('windows'))">
      <ItemGroup>
        <PackageReference Include="Eto.Platform.Windows" Version="2.9.0" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Eto.Forms" Version="2.9.0" />
        <PackageReference Include="Eto.Platform.Gtk" Version="2.9.0" />
      </ItemGroup>
    </Otherwise>
  </Choose>

</Project>
