<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TNAB.Browser\TNAB.Browser.csproj" />
    <ProjectReference Include="..\TNAB.Network\TNAB.Network.csproj" />
    <ProjectReference Include="..\TNAB.Renderer.Skia\TNAB.Renderer.Skia.csproj" />
  </ItemGroup>

</Project>
