<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TNAB.Streams\TNAB.Streams.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Agent.css" />
  </ItemGroup>

</Project>
